[tool.poetry]
name = "openbb-yfinance"
version = "1.2.1"
description = "yfinance extension for OpenBB"
authors = ["OpenBB Team <hello@openbb.co>"]
license = "AGPL-3.0-only"
readme = "README.md"
packages = [{ include = "openbb_yfinance" }]

[tool.poetry.dependencies]
python = "^3.8"
yfinance = "^0.2.27"
openbb-core = "^1.2.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_provider_extension"]
yfinance = "openbb_yfinance:yfinance_provider"
