[tool.poetry]
name = "openbb-sec"
version = "1.2.1"
description = "SEC extension for OpenBB"
authors = ["OpenBB Team <hello@openbb.co>"]
license = "AGPL-3.0-only"
readme = "README.md"
packages = [{ include = "openbb_sec" }]

[tool.poetry.dependencies]
python = ">=3.8,<3.12"
openbb-core = "^1.2.3"
aiohttp-client-cache = "^0.11.0"
aiosqlite = "^0.20.0"
xmltodict = "^0.13.0"
bs4 = "^0.0.2"
lxml = "^5.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_provider_extension"]
sec = "openbb_sec:sec_provider"
